const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");
const vm = require("node:vm");
const { pathToFileURL } = require("node:url");

const root = path.resolve(__dirname, "..", "..");
const source = fs.readFileSync(path.join(root, "free-table.js"), "utf8");
const mediaModule = import(pathToFileURL(path.join(root, "free-table-media.mjs")).href);
// Real 1x1 PNG and JPEG files generated by the Windows image encoder.
const PNG = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAANSURBVBhXY2Bg+P8fAAMCAf/Jsq3uAAAAAElFTkSuQmCC", "base64");
const VALID_JPEG = Buffer.from("/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAABAAEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD896KKK/1TPhz/2Q==", "base64");
const metadata = { transferId: "ft_0123456789abcdef01234567", ownerUid: "sender", sessionId: "session_123" };

function functionSource(start, end) {
  const startAt = source.indexOf(start);
  const endAt = source.indexOf(end, startAt);
  assert.ok(startAt >= 0 && endAt > startAt);
  return source.slice(startAt, endAt);
}

function crc32(bytes) {
  let result = 0xffffffff;
  for (const byte of bytes) {
    result ^= byte;
    for (let bit = 0; bit < 8; bit += 1) result = (result >>> 1) ^ ((result & 1) ? 0xedb88320 : 0);
  }
  return (result ^ 0xffffffff) >>> 0;
}

function editedPngHeader(edit) {
  const bytes = Buffer.from(PNG);
  edit(bytes);
  bytes.writeUInt32BE(crc32(bytes.subarray(12, 29)), 29);
  return bytes;
}

function preparationHarness(media, processor) {
  const calls = [];
  const revoked = [];
  const context = vm.createContext({
    FREE_TABLE_IMAGE_MAX_BYTES: media.FREE_TABLE_IMAGE_MAX_BYTES,
    FREE_TABLE_IMAGE_MAX_SIDE: media.FREE_TABLE_IMAGE_MAX_SIDE,
    URL: { revokeObjectURL: (url) => revoked.push(url) },
    shared: () => ({ processImageFile: async (file, position, options) => {
      calls.push({ file, position, ...options });
      return processor(calls.length);
    } }),
  });
  vm.runInContext(functionSource("async function prepareMediaAsset", "async function handleMediaFile"), context);
  return { context, calls, revoked };
}

test("ordinary compressed images stop after one conversion and preserve the actual MIME", async () => {
  const media = await mediaModule;
  const original = new Blob([PNG], { type: "image/png" });
  for (const mime of ["image/webp", "image/png", "image/jpeg"]) {
    const output = new Blob([Uint8Array.of(1, 2, 3)], { type: mime });
    const harness = preparationHarness(media, () => ({ blob: output, url: "blob:converted" }));
    const asset = await harness.context.prepareMediaAsset(original, "image");
    assert.equal(harness.calls.length, 1);
    assert.equal(harness.calls[0].maxSide, 1280);
    assert.equal(harness.calls[0].file, original);
    assert.equal(asset.blob, output);
    assert.equal(asset.mime, mime);
    assert.deepEqual(harness.revoked, ["blob:converted"]);
  }
});

for (const fitsAt of [2, 3]) {
  test(`large fallback photos stop at attempt ${fitsAt}, preserve original bytes, and release all temporary URLs`, async () => {
    const media = await mediaModule;
    const original = new Blob([PNG], { type: "image/png" });
    const finalBlob = new Blob([PNG], { type: "image/png" });
    const oversized = new Blob([new Uint8Array(media.FREE_TABLE_IMAGE_MAX_BYTES + 1)], { type: "image/png" });
    const harness = preparationHarness(media, (attempt) => ({
      blob: attempt === fitsAt ? finalBlob : oversized, url: `blob:attempt-${attempt}`,
    }));
    const asset = await harness.context.prepareMediaAsset(original, "image");
    assert.deepEqual(harness.calls.map((call) => call.maxSide), [1280, 960, 640].slice(0, fitsAt));
    assert.ok(harness.calls.every((call) => call.file === original && call.position === 0 && call.quality === 0.82));
    assert.equal(asset.blob, finalBlob);
    assert.equal(asset.mime, "image/png");
    assert.deepEqual(harness.revoked, Array.from({ length: fitsAt }, (_, index) => `blob:attempt-${index + 1}`));
    assert.deepEqual(Buffer.from(await original.arrayBuffer()), PNG);
  });
}

test("large photos still over the cap at 640px fail after exactly three attempts and release every URL", async () => {
  const media = await mediaModule;
  const oversized = new Blob([new Uint8Array(media.FREE_TABLE_IMAGE_MAX_BYTES + 1)], { type: "image/png" });
  const harness = preparationHarness(media, (attempt) => ({ blob: oversized, url: `blob:large-${attempt}` }));
  await assert.rejects(harness.context.prepareMediaAsset(new Blob([PNG]), "image"), /縮小しても約1.5MB/);
  assert.deepEqual(harness.calls.map((call) => call.maxSide), [1280, 960, 640]);
  assert.deepEqual(harness.revoked, ["blob:large-1", "blob:large-2", "blob:large-3"]);
});

test("image conversion failure stops retrying and releases each returned preview URL", async () => {
  const media = await mediaModule;
  const oversized = new Blob([new Uint8Array(media.FREE_TABLE_IMAGE_MAX_BYTES + 1)], { type: "image/png" });
  const harness = preparationHarness(media, (attempt) => {
    if (attempt === 2) throw new Error("fixture conversion failed");
    return { blob: oversized, url: "blob:oversized" };
  });
  await assert.rejects(harness.context.prepareMediaAsset(new Blob([PNG]), "image"), /fixture conversion failed/);
  assert.equal(harness.calls.length, 2);
  assert.deepEqual(harness.revoked, ["blob:oversized"]);
  const invalid = preparationHarness(media, () => ({ url: "blob:invalid" }));
  await assert.rejects(invalid.context.prepareMediaAsset(new Blob([PNG]), "image"), /変換できません/);
  assert.deepEqual(invalid.revoked, ["blob:invalid"]);
});

for (const [mime, bytes] of [["image/png", PNG], ["image/jpeg", VALID_JPEG]]) {
  test(`free table safely transfers real ${mime} after peer capability confirmation`, async () => {
    const media = await mediaModule;
    const asset = { kind: "image", mime, duration: 0, blob: new Blob([bytes], { type: mime }) };
    const resource = await media.createLocalFreeTableMediaResource(asset, metadata, { urlApi: { createObjectURL: () => "blob:local" } });
    assert.equal(resource.mime, mime);
    assert.equal(resource.blob.type, mime);
    const sent = [];
    await media.sendFreeTableMedia({ readyState: "open", bufferedAmount: 0, send: (value) => sent.push(value) }, asset, metadata, {
      peerImageMimes: [mime], chunkBytes: 7,
    });
    const transfer = media.createIncomingFreeTableMediaTransfer(JSON.parse(sent[0]), {
      expectedOwnerUid: metadata.ownerUid, expectedSessionId: metadata.sessionId,
    });
    for (const chunk of sent.slice(1, -1)) await media.appendIncomingFreeTableMediaChunk(transfer, chunk);
    const received = await media.finishIncomingFreeTableMediaTransfer(transfer, JSON.parse(sent.at(-1)), {
      urlApi: { createObjectURL: () => "blob:received" },
    });
    assert.equal(received.mime, mime);
    assert.equal(received.blob.type, mime);
    assert.deepEqual(Buffer.from(await received.blob.arrayBuffer()), bytes);
  });

  test(`free table sends no ${mime} bytes to an old or unconfirmed peer`, async () => {
    const media = await mediaModule;
    for (const peerImageMimes of [undefined, [], ["image/webp"]]) {
      const sent = [];
      await assert.rejects(media.sendFreeTableMedia({ readyState: "open", send: (value) => sent.push(value) }, {
        kind: "image", mime, blob: new Blob([bytes], { type: mime }),
      }, metadata, { peerImageMimes }), /ページを再読み込み/);
      assert.equal(sent.length, 0);
    }
  });
}

test("free table keeps MIME, byte, dimension, and transfer-context limits for fallback images", async () => {
  const media = await mediaModule;
  for (const [bytes, mime] of [[PNG, "image/webp"], [PNG, "image/jpeg"], [VALID_JPEG, "image/png"], [Buffer.from("<svg/>"), "image/png"]]) {
    assert.throws(() => media.verifyFreeTableMediaBytes(bytes, { kind: "image", mime }), /実データ/);
  }
  assert.throws(() => media.verifyFreeTableMediaBytes(new Uint8Array(media.FREE_TABLE_IMAGE_MAX_BYTES + 1), {
    kind: "image", mime: "image/png",
  }), /1.5MB/);
  const largePng = editedPngHeader((bytes) => bytes.writeUInt32BE(1281, 16));
  assert.throws(() => media.verifyFreeTableMediaBytes(largePng, { kind: "image", mime: "image/png" }), /1280px/);
  const largeJpeg = Buffer.from(VALID_JPEG);
  const frame = largeJpeg.indexOf(Buffer.from([0xff, 0xc0]));
  assert.ok(frame > 0);
  largeJpeg.writeUInt16BE(1281, frame + 7);
  assert.throws(() => media.verifyFreeTableMediaBytes(largeJpeg, { kind: "image", mime: "image/jpeg" }), /1280px/);
  const outgoing = await media.createOutgoingFreeTableMediaTransfer({ kind: "image", mime: "image/png", blob: new Blob([PNG], { type: "image/png" }) }, metadata);
  for (const expected of [{ expectedOwnerUid: "other", expectedSessionId: metadata.sessionId }, { expectedOwnerUid: metadata.ownerUid, expectedSessionId: "other" }]) {
    assert.throws(() => media.createIncomingFreeTableMediaTransfer(outgoing.transfer, expected), /同席者以外|別の自由卓/);
  }
});

test("free table rejects truncated or forged PNG structures and JPEG segments", async () => {
  const { verifyFreeTableMediaBytes } = await mediaModule;
  const corruptPngCrc = Buffer.from(PNG);
  corruptPngCrc[16] ^= 1;
  const badPngLength = Buffer.from(PNG);
  badPngLength.writeUInt32BE(0xffffffff, 8);
  const invalidPngHeader = editedPngHeader((bytes) => { bytes[26] = 1; });
  const zeroPng = editedPngHeader((bytes) => bytes.writeUInt32BE(0, 16));
  for (const bytes of [PNG.subarray(0, 8), PNG.subarray(0, 29), PNG.subarray(0, -1), corruptPngCrc, badPngLength, invalidPngHeader, zeroPng]) {
    assert.throws(() => verifyFreeTableMediaBytes(bytes, { kind: "image", mime: "image/png" }), /PNG|寸法/);
  }
  const badJpegLength = Buffer.from(VALID_JPEG);
  badJpegLength.writeUInt16BE(0xffff, 4);
  const badJpegFrame = Buffer.from(VALID_JPEG);
  badJpegFrame[badJpegFrame.indexOf(Buffer.from([0xff, 0xc0])) + 9] = 255;
  for (const bytes of [VALID_JPEG.subarray(0, 100), VALID_JPEG.subarray(0, 3), VALID_JPEG.subarray(0, -2), badJpegLength, badJpegFrame]) {
    assert.throws(() => verifyFreeTableMediaBytes(bytes, { kind: "image", mime: "image/jpeg" }), /JPEG/);
  }
});

test("free table capability claims are fenced to the exact peer and session", async () => {
  const media = await mediaModule;
  const message = media.freeTableMediaCapabilitiesMessage(metadata);
  const expected = { expectedOwnerUid: metadata.ownerUid, expectedSessionId: metadata.sessionId };
  assert.deepEqual(media.readFreeTableMediaCapabilities(message, expected), ["image/webp", "image/png", "image/jpeg"]);
  for (const change of [{ ownerUid: "other" }, { sessionId: "other" }, { protocolVersion: 2 }, { imageMimes: ["image/svg+xml"] }, { imageMimes: "image/png" }, { requestReply: "yes" }]) {
    assert.throws(() => media.readFreeTableMediaCapabilities({ ...message, ...change }, expected), /確認/);
  }
  assert.throws(() => media.readFreeTableMediaCapabilities(message, {}), /確認/);
});

test("free table capability exchange replies once and resets on channel replacement and close", async () => {
  const media = await mediaModule;
  const errors = [];
  const state = {
    uid: "receiver", opponentUid: "sender", sessionId: metadata.sessionId, sessionGeneration: 1,
    mediaGeneration: 0, mediaChannel: null, mediaReady: false, peer: null, peerGeneration: 1,
    peerRecoveryAttempts: 0, peerImageMimes: [],
  };
  const context = vm.createContext({
    ...media, state, console, window: { clearTimeout() {} },
    FREE_TABLE_CONTROL_MAX_CHARS: 4000,
    sessionContextIsCurrent: (id, generation) => id === state.sessionId && generation === state.sessionGeneration,
    peerContextIsCurrent: () => true, clearPeerRecoveryTimer() {}, render() {},
    reportFreeTableP2pDiagnostic: async () => {}, confirmArrivalAfterP2p: async () => {},
    handleSessionAuxiliaryError: (error) => errors.push(error), isHost: () => false,
  });
  vm.runInContext(
    functionSource("function configureMediaDataChannel", "function arrivalFailureIsTerminal")
    + functionSource("async function handleMediaChannelMessage", "function currentRecordExpiry"), context,
  );
  const makeChannel = () => ({
    label: media.FREE_TABLE_MEDIA_CHANNEL_LABEL, readyState: "open", sent: [],
    send(message) { this.sent.push(JSON.parse(message)); }, close() { this.readyState = "closed"; },
  });
  const first = makeChannel();
  context.configureMediaDataChannel(first);
  assert.equal(first.sent.length, 1);
  assert.equal(first.sent[0].requestReply, true);
  const request = media.freeTableMediaCapabilitiesMessage(metadata);
  await context.handleMediaChannelMessage(JSON.stringify(request), first);
  assert.equal(first.sent.length, 2);
  assert.equal(first.sent[1].requestReply, false);
  await context.handleMediaChannelMessage(JSON.stringify({ ...request, requestReply: false }), first);
  assert.equal(first.sent.length, 2, "a response must never cause a response loop");
  assert.ok(state.peerImageMimes.includes("image/png"));
  const staleMessageHandler = first.onmessage;
  const second = makeChannel();
  context.configureMediaDataChannel(second);
  assert.equal(second.sent.length, 1, "replacement announces even when the old channel was ready");
  assert.equal(state.peerImageMimes.length, 0);
  staleMessageHandler({ data: JSON.stringify(request) });
  await context.handleMediaChannelMessage(JSON.stringify(request), first, { mediaGeneration: 0 });
  assert.equal(state.peerImageMimes.length, 0, "old channel must not restore capability claims");
  await context.handleMediaChannelMessage(JSON.stringify(request), second);
  assert.ok(state.peerImageMimes.includes("image/png"));
  second.onclose();
  assert.equal(state.peerImageMimes.length, 0);
  assert.deepEqual(errors, []);
});
